#
# gp-base-devenv
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

FROM ubuntu:22.04

LABEL org.opencontainers.image.description "Base image using Ubuntu for building VS Code Dev Container"

# Timezone
ENV TZ="Europe/Paris"

# For persistent volumes
VOLUME [ "/home" ]

# Remove unwanted files (not possible via .dockerignore)
RUN rm -rf scripts

# Set the timezone
RUN apt-get update && \
    apt-get install tzdata -y

# Set locales
RUN apt-get update && \
    apt-get install locales && \
    dpkg-reconfigure locales

# Update all
RUN apt-get update && \
    apt-get full-upgrade -y

# Install essential packages
RUN apt-get update && \
    apt-get install -y build-essential \
                       automake \
                       autoconf \
                       checkinstall \ 
                       curl \
                       wget \
                       software-properties-common \ 
                       less \
                       ncdu \
                       nmap \
                       zsh \
                       vim \
                       git \
                       unzip \
                       usbutils \
                       tmux \
                       htop \
                       neofetch \
                       gdb && \
    apt-get autoclean -y && \
    apt-get autoremove -y

# Starship
RUN curl -sS https://starship.rs/install.sh -o install.sh && \
    sh install.sh --yes && \
    rm install.sh

# Setup sudo
RUN apt-get update && \
    apt-get install -y sudo
RUN echo "vscode ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode

# Default for users
WORKDIR /etc/skel
COPY dist/.zshrc .
COPY dist/.vimrc .
COPY dist/.tmux.conf .
COPY dist/setup.sh .
RUN mkdir /etc/skel/.config
COPY dist/starship.toml /etc/skel/.config
RUN curl -fLo /etc/skel/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN git clone https://github.com/tmux-plugins/tpm /etc/skel/.tmux/plugins/tpm

# Adjust root user
WORKDIR /root
RUN chsh -s /bin/zsh root
COPY dist/.zshrc .
COPY dist/.vimrc .
COPY dist/.tmux.conf .
COPY dist/setup.sh .
RUN mkdir ~/.config
COPY dist/starship.toml /etc/skel/.config
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Add vscode user
RUN useradd -s /bin/zsh -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode
USER vscode
WORKDIR /home/vscode
