#
# gp-base-devenv
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Build and validate

name: release

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Push ghcr.io/gpfister/gp-base-devenv
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ubuntu_version: ['20.04', '22.04']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup buildx
        run: (cd src && ./scripts/buildx/setup.sh)
      - name: Authenticating
        run: echo $GHCR_IO_TOKEN | docker login ghcr.io -u gpfister --password-stdin
        env:
          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
      - name: Build using ubuntu:${{ matrix.ubuntu_version }} and push
        run: (cd src && ./scripts/buildx/push.sh ${{ matrix.ubuntu_version }})
      - name: Dispatch to other repository
        run: |
          curl -X POST /
               -u "${{ secrets.GIT_CREDENTIALS }}" /
               -H "Accept:application/vnd.github" /
               -H "Content-Type:application/json" /
               https://api.github.com/gpfister/gp-firebase-devenv/.github/workflows/dispatch.yaml/dispatches /
               --data '{"ref": "master", "ubuntu": "${{ matrix.ubuntu-version }}" }' && \
          curl -X POST /
               -u "${{ secrets.GIT_CREDENTIALS }}" /
               -H "Accept:application/vnd.github" /
               -H "Content-Type:application/json" /
               https://api.github.com/gpfister/gp-docker-devenv/.github/workflows/dispatch.yaml/dispatches /
               --data '{"ref": "master", "ubuntu": "${{ matrix.ubuntu-version }}" }'
        env:
          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
